spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
  web.resources.static-locations: file:./app/
cds:
  data-source.auto-config.enabled: false
  security:
    mock:
      users:
        - name: klaus
          password: pass_klaus
          additional:
            firstName: Klaus
            lastName: Sussard
            email: Klaus.Sussard@mail.com
        - name: mia
          password: pass_mia
          roles:
            - Administrators
          additional:
            firstName: Mia
            lastName: Bonnellac
            email: Mia.Bonnellac@mail.com
        - name: sabine
          pass: sabine_pass
          roles:
            - Administrators
          additional:
            firstName: sabine
            lastName: Bonnellac
            email: sabine.Bonellac@gmail.com
